from enum import IntEnum


class AddressUserType(IntEnum):
    EXCHANGE_USER = 0
    EXCHANGE_DISTRIBUTION_LIST = 1
    EXCHANGE_PUBLIC_FOLDER = 2
    EXCHANGE_AGENT = 3
    EXCHANGE_ORGANIZATION = 4
    EXCHANGE_REMOTE_USER = 5
    OUTLOOK_CONTACT = 10
    OUTLOOK_DISTRIBUTION_LIST = 11
    LDAP = 20
    SMTP = 30
    OTHER = 40
